### ISSUE TITLE
无法获取背景

### ISSUE THREAD

**Issue by zeruishao** [aimeng100/WeSamBE#1]
在运行bgfg_segm.cpp代码的时候，获取的背景均为像素值为205的图像。我是在opencv2 Debug x86 VS2015下调试运行的代码，掩模可以正常获取，但是背景一直是“白图”，请问作者这是什么问题？

**Comment by Ton-lee** [comment]
文件 WeSamBE-master\BackgroundSubtractorSuBSENSE.cpp 第 712 行似乎应该是 *3，而不是 *4。表示一个像素值所存储的浮点数，即通道数。
